directory: ~/Nuttyverse/Music/
library: ~/Nuttyverse/Data/beets/library.db
plugins: badfiles chroma duplicates edit fetchart mbsync scrub
paths:
  singleton: $albumartist/Singles/$title
import:
  move: yes
