#!/usr/bin/env -S just --justfile

set export
set shell := ["nix", "develop", "-u", "PATH", "-c", "fish", "-c"]

project := `basename (pwd)`

@develop:
	echo "[INFO] Entering $project shell…"
	./scripts/develop.fish

@install:
	echo "[INFO] Installing $project…"
	ln -is (pwd)/config.yaml ~/.config/beets/config.yaml
	./scripts/install.fish

@build: install
	echo "[INFO] Building $project…"

@test: build
	echo "[INFO] Testing $project…"
	./scripts/test.fish

@deploy: test
	echo "[INFO] Deploying $project…"

@clean:
	echo "[INFO] Cleaning $project…"
	rm -frv .venv/

@update: clean
	echo "[INFO] Updating $project…"
	nix flake update
	nixfmtty flake.lock
	./scripts/update.fish
