#!/usr/bin/env -S just --justfile

set shell := ["fish", "-c"]

develop:
	@echo "[INFO] Entering nixfmtty shell…"
	@nix develop --command fish

build:
	@echo "[INFO] Building nixfmtty…"
	@nix build
	@nixfmtty flake.lock

test: build
	@echo "[INFO] Testing nixfmtty…"
	@nix develop --unset PATH --command ./scripts/test.fish

deploy: test
	@echo "[INFO] Deploying nixfmtty…"

update:
	@echo "[INFO] Updating nixfmtty…"
	@nix flake update
	@nixfmtty flake.lock
