#!/usr/bin/env -S just --justfile

set export
set shell := ["fish", "-c"]

project := `basename (pwd)`

@develop:
	echo "[INFO] Entering $project shell…"
	nix develop -c fish

@build:
	echo "[INFO] Building $project…"
	nix build
	nix develop -c nixfmtty flake.lock

@test: build
	echo "[INFO] Testing $project…"
	nix develop -u PATH -c ./scripts/test.fish

@deploy: test
	echo "[INFO] Deploying $project…"

@clean:
	echo "[INFO] Cleaning $project…"
	rm -fv result

@update:
	echo "[INFO] Updating $project…"
	nix flake update
	nix develop -c nixfmtty flake.lock
