#!/usr/bin/env -S just --justfile

set export
set shell := ["fish", "--no-config", "--command"]

project := `basename (pwd)`

@ci *COMMAND:
	echo "[INFO] Entering the Nuttyverse CI…"
	nix develop \
		--no-update-lock-file \
		--ignore-environment \
		--command {{COMMAND}}

@develop:
	echo "[INFO] Entering $project shell…"
	nix develop --command fish

@install:
	echo "[INFO] Installing $project…"
	mkdir --parents ~/.config/ghostty
	ln \
		--interactive \
		--no-target-directory \
		--symbolic \
		--verbose \
		(pwd)/config ~/.config/ghostty/config

@update:
	echo "[INFO] Updating $project…"
	nix flake update
	nixfmtty flake.lock
