#!/usr/bin/env -S just --justfile

set export
set shell := ["fish", "--no-config", "--command"]

project := `basename (pwd)`

@install:
	echo "[INFO] Installing $project…"
	ln \
		--interactive \
		--no-target-directory \
		--symbolic \
		--verbose \
		(pwd) ~/.config/ghostty
