#!/usr/bin/env -S just --justfile

set export
set shell := ["nix", "develop", "-c", "fish", "-c"]

project := `basename (pwd)`

@develop:
	echo "[INFO] Entering $project shell…"
	nix develop -c fish

@install:
	echo "[INFO] Installing $project…"
	ln -isvT (pwd) ~/.config/nvim

@build: install
	echo "[INFO] Building $project…"

@test: build
	echo "[INFO] Testing $project…"

@deploy: test
	echo "[INFO] Deploying $project…"

@clean:
	echo "[INFO] Cleaning $project…"

@update:
	echo "[INFO] Updating $project…"
	nix flake update
	nixfmtty flake.lock
