FROM rust:1.87-slim

# Install development dependencies.
RUN apt-get update && \
	apt-get install -y pkg-config libssl-dev && \
	cargo install cargo-watch && \
	rm -rf /var/lib/apt/lists/*

# Set working directory.
WORKDIR /api

# Copy Cargo files for dependency caching.
COPY Cargo.toml Cargo.lock .

# Create empty src/main.rs to build dependencies.
RUN mkdir -p src && \
	echo "fn main() {}" > src/main.rs && \
	cargo build && \
	rm -rf src

# Expose Axum's default port.
EXPOSE 3000

# Use cargo watch for auto-reloading in development.
CMD ["cargo", "watch", "-x", "run"]
