[tarpaulin]
# Output format: "Xml", "Json", "Html", "Lcov", "Stdout", "StdoutColored".
output = ["Html", "StdoutColored"]

# Generate a report in the specified directory.
output-dir = "target/coverage"

# Exclude test files from coverage.
exclude-files = ["tests/*", "benches/*"]

# Exclude lines containing these patterns.
exclude-patterns = ["#[cfg(test)]", "#[test]"]

# Fail if coverage is below this threshold (0-100).
fail-under = 80

# Timeout for test execution (in seconds).
timeout = "60s"

# Run tests in release mode.
release = true

# Generate a coverage report for all targets.
all-targets = true 